import "./index.css";
import ReactQueryWrapper from "./reactQueryWrapper";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <ReactQueryWrapper>
        <body>
          {children}
          <div id="modal_root"></div>
        </body>
      </ReactQueryWrapper>
    </html>
  );
}
