import Footer from "@/components/footer/footer";
import Head from "next/head";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <Head>
        <link rel="stylesheet" href="@/common.css" />
        <link rel="stylesheet" href="@/index.css" />
      </Head>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
