import Footer from "@/components/footer/footer";
import "./index.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        {children}
        <Footer />
        <div id="modal_root"></div>
      </body>
    </html>
  );
}
